"""Initial-Migrate

Revision ID: 906f30ece373
Revises: 
Create Date: 2022-03-21 14:45:04.641973

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '906f30ece373'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('password_hash', sa.String(length=120), nullable=False))
    op.drop_column('users', 'password')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('password', sa.VARCHAR(length=120), nullable=False))
    op.drop_column('users', 'password_hash')
    # ### end Alembic commands ###
